language: python
sudo: required
python:
  - "2.7"

install: 
  - "pip install -r requirements.txt"
  - "pip install -r requirements-test.txt"
before_script:
  - "cd nengo_gui"
  - wget http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - "cd .."
  - "python setup.py develop"
  - "export DISPLAY=:99.0"
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/cucumber_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16
  - sleep 3 # give xvfb some time to start
  - "wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar"
  - "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  - "nengo_gui --no-browser --auto-shutdown 0 &"#starts up nengo_gui
  - sleep 2
# command to run tests
script: 
  - py.test
